# Generated by Django 3.1.7 on 2021-04-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=50)),
                ('polarity', models.FloatField()),
                ('subjectivity', models.FloatField()),
            ],
        ),
    ]
